# Generated by Django 5.1.4 on 2025-01-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_appointment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="ContactMessage",
        ),
    ]
